from pandas import DataFrame
from google.cloud import bigquery
from mlflow_training_tracking.mixin.bigquery_mixin import BigQueryMixin
from mlflow_training_tracking.helpers.bigquery_location import BigQueryLocation
from mlflow_training_tracking.service_implementations.model.bigquery_base import ModelOperatorBigQueryLocation


class ClassificationModelOperatorBigQueryLocation(ModelOperatorBigQueryLocation):
    pass
